# Generated by Django 2.2.9 on 2020-10-19 10:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20, verbose_name='asin')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('company', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='费用')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='提交日期')),
                ('sh_remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='审核备注')),
                ('yy_remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='运营备注')),
                ('status', models.CharField(choices=[('0', '待提交'), ('1', '待完成'), ('2', '已完成')], default='0', max_length=10, verbose_name='状态')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL, verbose_name='运营人员')),
            ],
        ),
    ]
